# Site settings
title: ClassTracks
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Blend your foreign language classroom.
  Spend less time drilling, more time teaching. Transform your classroom with ClassTracks.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.myclasstracks.com" # the base hostname & protocol for your site
twitter_username: classtracks
facebook_username: ClassTracks
#github_username:  jekyll

# Build settings
markdown: kramdown
highlighter: rouge 
# syntax highlighter for windows substitute for Pygments (jekyll default-requires Python installation) 
